### PR TITLE
Fix request errors on workspace & findNextWorkspace

### LINKED ISSUE #764: Fix server failed response rate
Although #763 reduced the error rate substantially - as seem by before/after Friday - there are still a substantial amount of timeout errors.
image

It seems our timeout is ~30 seconds. This seems like a good upper bound: https://ux.stackexchange.com/questions/45323/whats-reasonable-time-lag-before-displaying-a-timeout-message.

Heroku gives us db-level analytics via `heroku pg:outliners -a mosaic-prod` on which queries are the most expensive:
image
More info is available here: https://data.heroku.com/datastores/b2ed9b32-2f37-4563-a249-e580d25e5fda#diagnose

### PR DESCRIPTION
**Pull request by andrewschreiber**
closes #764

### CODE REVIEW

File: server/lib/models/workspace.ts [hunk 1]
```diff
@@ -208,6 +208,11 @@ export default class Workspace extends Model<Workspace> {
       // not the pointer containing the honest answer candidate.
       // This pointer is contained in the malicious question.
       const maliciousWorkspace = await Workspace.findByPk(workspace.parentId);
+      if (!maliciousWorkspace) {
```
Comment (zjmiller) [inline server/lib/models/workspace.ts]: I would chance this condition to `!maliciousWorkspace || !maliciousWorkspace.isEligibleForMaliciousOracle)`. So now even if a workspace has a parent, if this parent isn't malicious then we stop here.

File: server/lib/models/workspace.ts [hunk 2]
```diff
@@ -250,6 +256,9 @@ export default class Workspace extends Model<Workspace> {
       // contains the honest answer candidate, and this first appears in the
       // malicious question.
       const maliciousWorkspace = await Workspace.findByPk(workspace.parentId);
+      if (!maliciousWorkspace) {
```
Comment (zjmiller) [inline server/lib/models/workspace.ts]: Same as above.
